name: Build and Package Go Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Go App and Create Debian Package
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    # Step 3: Build the Go application
    - name: Build the Go application for ${{ matrix.arch }}
      run: |
        GOARCH=${{ matrix.arch }} GOOS=linux go build -o ret3iac-linux-${{ matrix.arch }}

    # Step 4: Create Debian package directory structure
    - name: Create Debian package structure
      run: |
        mkdir -p debian_package/usr/local/bin
        mkdir -p debian_package/DEBIAN
        cp ret3iac-linux-${{ matrix.arch }} debian_package/usr/local/bin/ret3iac
        chmod 755 debian_package/usr/local/bin/ret3iac

    # Step 5: Create the control file for the Debian package
    - name: Create control file
      run: |
        echo "Package: ret3iac" > debian_package/DEBIAN/control
        echo "Version: 1.0.0" >> debian_package/DEBIAN/control
        echo "Section: base" >> debian_package/DEBIAN/control
        echo "Priority: optional" >> debian_package/DEBIAN/control
        echo "Architecture: ${{ matrix.arch }}" >> debian_package/DEBIAN/control
        echo "Maintainer: Your Name <your.email@example.com>" >> debian_package/DEBIAN/control
        echo "Description: Ret3iac - An Infrastructure as Code CLI tool for AWS." >> debian_package/DEBIAN/control

    # Step 6: Build the .deb package
    - name: Build the Debian package
      run: dpkg-deb --build debian_package ret3iac_${{ matrix.arch }}.deb

    # Step 7: Upload the Debian package as a build artifact
    - name: Upload .deb package artifact
      uses: actions/upload-artifact@v3
      with:
        name: ret3iac-${{ matrix.arch }}.deb
        path: ret3iac_${{ matrix.arch }}.deb
